//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Car
    {
        public int CarID { get; set; }
        public int ManufacturerID { get; set; }
        public int ModelID { get; set; }
        public int EngineID { get; set; }
        public int ColourID { get; set; }

        [DisplayName("Mileage")]
        [Range(0,100000)]
        public Nullable<int> Mileage { get; set; }

        [DisplayName("Current Condition")]
        [StringLength(100)]
        public string Condition { get; set; }
        public int StatusID { get; set; }

        [DisplayName("Approximate Value")]
        public Nullable<decimal> ApproxValue { get; set; }

        [DisplayName("MOT Due Date")]
        public Nullable<System.DateTime> MOTDueDate { get; set; }
    
        public virtual Colour Colour { get; set; }
        public virtual Engine Engine { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Model Model { get; set; }
        public virtual Status Status { get; set; }
    }
}
